# Generated by Django 4.2.1 on 2023-05-27 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_candidate_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="job",
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
