# Generated by Django 4.2.1 on 2023-05-29 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0006_candidate_experience_candidate_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="file",
            field=models.FileField(default=django.utils.timezone.now, upload_to=""),
            preserve_default=False,
        ),
    ]
