# Generated by Django 4.2.1 on 2023-05-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0008_candidate_databases_candidate_frameworks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="Situation",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
                null=True,
            ),
        ),
    ]
