# Generated by Django 4.2.1 on 2023-05-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0009_alter_candidate_situation"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="company_note",
            field=models.TextField(blank=True),
        ),
    ]
