# Generated by Django 4.2.1 on 2023-05-30 19:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0010_candidate_company_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="age",
        ),
        migrations.AddField(
            model_name="candidate",
            name="birth",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Birthday"
            ),
            preserve_default=False,
        ),
    ]
