# Generated by Django 4.2.1 on 2023-05-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0013_candidate_image_alter_candidate_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="Travel",
            new_name="travel",
        ),
    ]
