# Generated by Django 4.2.1 on 2023-06-02 19:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0017_alter_candidate_status_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="databases",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("MySql", "MySql"),
                    ("Postgree", "Postgree"),
                    ("MongoDB", "MongoDB"),
                    ("SqLite3", "SqLite3"),
                    ("Oracle", "Oracle"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="frameworks",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Laravel", "Laravel"),
                    ("Angular", "Angular"),
                    ("Django", "Django"),
                    ("Flask", "Flask"),
                    ("Vue", "Vue"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="languages",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Python", "Python"),
                    ("Javascript", "Javascript"),
                    ("Java", "Java"),
                    ("C++", "C++"),
                    ("Ruby", "Ruby"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="libraries",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("Ajax", "Ajax"),
                    ("Jquery", "Jquery"),
                    ("ReactJs", "ReactJs"),
                    ("Chart.js", "Chart.js"),
                    ("Gsap", "Gsap"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="mobile",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("React native", "React native"),
                    ("Kivy", "Kivy"),
                    ("Flutter", "Flutter"),
                    ("Ionic", "Ionic"),
                    ("Xamarin", "Xamarin"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="others",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("UML", "UML"),
                    ("SQL", "SQL"),
                    ("Docker", "Docker"),
                    ("GIT", "GIT"),
                    ("GraphQL", "GraphQL"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
